import type { PictureImage, PictureMovement } from "@webxlights/engine";

// The picture library: small cartoon sprites for the matrix, drawn here as text, one character
// a pixel. Pixel art rather than generated images: it reads on a 32-64 pixel matrix, its frames
// line up exactly (a loop that shifts a pixel between frames looks like a jitter on a matrix),
// it costs nothing, and every one is an original drawing. "." is off (black).
//
// A lyric word that names one of these (sprites.words) puts it on the matrix while it is sung
// (docs/MAGIC-SEQUENCE.md, "Pictures from the lyrics").

export interface Sprite {
  id: string;
  label: string;
  /** Lyric words that call it up, lower case. */
  words: string[];
  /** How it moves across the matrix while it plays. */
  movement: PictureMovement;
  fps: number;
  /** Colour per character beyond the shared ones. */
  colours?: Record<string, string>;
  /** Rows of characters, top first, every frame the same size. */
  frames: string[];
}

const SHARED: Record<string, string> = {
  W: "#ffffff", K: "#9a9a9a", k: "#4a4a4a", R: "#ff1010", r: "#a00000", G: "#10c010", g: "#086008",
  B: "#9a5a22", b: "#5c3410", T: "#e0b070", Y: "#ffc800", y: "#b08000", O: "#ff7a00", S: "#ffc8a0",
  U: "#2060ff", L: "#80c8ff", P: "#ff70b0", V: "#9040ff",
};

export const SPRITES: Sprite[] = [
  {
    id: "reindeer", label: "Reindeer", movement: "right", fps: 6,
    words: ["reindeer", "deer", "dasher", "dancer", "prancer", "vixen", "comet", "cupid", "donner", "blitzen", "antlers"],
    frames: [
`..................b..b..
.................b.bb.b.
..................bbbb..
...................BB...
..................BBBB..
..................BWBBk.
.................BBBBBkk
...............BBBB.....
..T...........BBB.......
..TBBBBBBBBBBBBBB.......
...BBBBBBBBBBBBBB.......
...BBTTTTTTTTTBBB.......
....BB.......BB.........
...B..B.....B..B........
..B....B...B....B.......
.b......b.b......b......`,
`..................b..b..
.................b.bb.b.
..................bbbb..
...................BB...
..................BBBB..
..................BWBBk.
.................BBBBBkk
...............BBBB.....
..T...........BBB.......
..TBBBBBBBBBBBBBB.......
...BBBBBBBBBBBBBB.......
...BBTTTTTTTTTBBB.......
....BB.......BB.........
....BB.......BB.........
....B.B.....B.B.........
....b..b....b..b........`,
    ],
  },
  {
    id: "sleigh", label: "Sleigh", movement: "fly", fps: 4,
    words: ["sleigh", "sled", "sledge", "sleighride", "dashing", "riding"],
    frames: [
`..........G.R.Y..........
.........GGRRRYY.........
.....R..RRRRRRRRRR.......
.....RRRRRRRRRRRRR.......
.....RYYYYYYYYYYYR.......
......RRRRRRRRRRRR.......
.......RRRRRRRRRR........
.......Y.......Y.........
..YYYYYYYYYYYYYYYYYYY....
.Y...................Y...
.........................
.W.......W.......W.......`,
`..........G.R.Y..........
.........GGRRRYY.........
.....R..RRRRRRRRRR.......
.....RRRRRRRRRRRRR.......
.....RYYYYYYYYYYYR.......
......RRRRRRRRRRRR.......
.......RRRRRRRRRR........
.......Y.......Y.........
..YYYYYYYYYYYYYYYYYYY....
.Y...................Y...
.........................
.....W.......W.......W...`,
    ],
  },
  {
    id: "santa", label: "Santa", movement: "bounce", fps: 3,
    words: ["santa", "claus", "nick", "nicholas", "kringle", "st"],
    frames: [
`.......RRRR.......W..
......RRRRRR.......S.
.....RRRRRRRW......S.
....WWWWWWWWW.....RR.
....SSSSSSSS.....RR..
....SkSSSSkS....RR...
....SSSOOSSS...RR....
...WWWWWWWWWW.RR.....
..WWWWWWWWWWWWR......
..RWWWWWWWWWWRR......
.RRRWWWWWWWWRRR......
.SRRRRRWRRRRRR.......
..RRkkkkkkkkRR.......
..RRRRYRRRRRR........
...RRRRRRRRRR........
...RRR....RRR........
...kkk....kkk........
..kkkk....kkkk.......`,
`.......RRRR..........
......RRRRRR.........
.....RRRRRRRW........
....WWWWWWWWW........
....SSSSSSSS.........
....SkSSSSkS.........
....SSSOOSSS.........
...WWWWWWWWWW........
..WWWWWWWWWWWW.......
..RWWWWWWWWWWRR......
.RRRWWWWWWWWRRRRRRS..
.SRRRRRWRRRRRR....W..
..RRkkkkkkkkRR.......
..RRRRYRRRRRR........
...RRRRRRRRRR........
...RRR....RRR........
...kkk....kkk........
..kkkk....kkkk.......`,
    ],
  },
  {
    id: "boots", label: "Boots on the roof", movement: "none", fps: 4,
    words: ["boots", "boot", "roof", "rooftop", "housetop", "rooftops", "footsteps", "stomp", "tap"],
    frames: [
`..........................
.....RR..........RR.......
.....RR..........RR.......
.....WW..........WW.......
.....kk..........kk.......
.....kk..........kk.......
.....kkkkk.......kk.......
.....kkkkkk......kkkkk....
.................kkkkkk...
..........................
rrrrrrrrrrrrrrrrrrrrrrrrrr
r.r.r.r.r.r.r.r.r.r.r.r.r.
.r.r.r.r.r.r.r.r.r.r.r.r.r`,
`..........................
.....RR...................
.....RR..........RR.......
.....WW..........RR.......
.....kk..........WW.......
.....kk..........kk.......
.....kk..........kk.......
.....kkkkk.......kk.......
.....kkkkkk......kkkkk....
.................kkkkkk...
rrrrrrrrrrrrrrrrrrrrrrrrrr
r.r.r.r.r.r.r.r.r.r.r.r.r.
.r.r.r.r.r.r.r.r.r.r.r.r.r`,
    ],
  },
  {
    id: "reindeer-car", label: "Reindeer driving a car", movement: "right", fps: 8,
    words: ["car", "drive", "driving", "drove", "truck", "road", "highway"],
    frames: [
`............b..b.........
...........b.bb.b........
............bbbb.........
.........RRRRBBRRRRR.....
........RR..BWBk...RR....
.......RR...BBBBkk..RR...
..RRRRRRRRRRRRRRRRRRRRRR.
.RRRRRRRRRRRRRRRRRRRRRRYY
.RRRRRRRRRRRRRRRRRRRRRRYY
.RRRRRRRRRRRRRRRRRRRRRRR.
..RRkkkRRRRRRRRRRkkkRRR..
...kKkKk........kKkKk....
....kkk..........kkk.....`,
`............b..b.........
...........b.bb.b........
............bbbb.........
.........RRRRBBRRRRR.....
........RR..BWBk...RR....
.......RR...BBBBkk..RR...
..RRRRRRRRRRRRRRRRRRRRRR.
.RRRRRRRRRRRRRRRRRRRRRRYY
.RRRRRRRRRRRRRRRRRRRRRRYY
.RRRRRRRRRRRRRRRRRRRRRRR.
..RRkkkRRRRRRRRRRkkkRRR..
...kkKkK........kkKkK....
....kkk..........kkk.....`,
    ],
  },
  {
    id: "snowman", label: "Snowman", movement: "bounce", fps: 3,
    words: ["snowman", "snowmen"],
    frames: [
`.......kkkk.......
.......kkkk.......
.....kkkkkkkk.....
......WWWWWW......
.....WWkWWkWW.....
.....WWWWOOOW.....
......WWWWWW......
....RRRRRRRR......
.b...WWWWWW....b..
..b.WWWkWWWW..b...
...bWWWWWWWWWb....
...WWWWkWWWWWW....
..WWWWWWWWWWWWW...
..WWWWWkWWWWWWW...
..WWWWWWWWWWWWW...
...WWWWWWWWWWW....`,
`.......kkkk.......
.......kkkk.......
.....kkkkkkkk.....
......WWWWWW......
.....WWkWWkWW.....
.....WWWWOOOW.....
......WWWWWW......
....RRRRRRRR...b..
.b...WWWWWW...b...
..b.WWWkWWWW.b....
...bWWWWWWWWb.....
...WWWWkWWWWWW....
..WWWWWWWWWWWWW...
..WWWWWkWWWWWWW...
..WWWWWWWWWWWWW...
...WWWWWWWWWWW....`,
    ],
  },
  {
    id: "bells", label: "Bells", movement: "none", fps: 4,
    words: ["bell", "bells", "jingle", "jingling", "ring", "ringing", "rings", "chime", "chimes", "ding", "dong"],
    frames: [
`.........RRRR.........
........RR..RR........
.......GG....GG.......
......YY......YY......
.....YYYY....YYYY.....
....YYYYYY..YYYYYY....
....YYYYYY..YYYYYY....
...YYYYYYYYYYYYYYYY...
...YYYYYYYYYYYYYYYY...
..YYYYYYYYYYYYYYYYYY..
..yyyyyyy....yyyyyyy..
.....yy........yy.....`,
`.........RRRR.........
........RR..RR........
......GG......GG......
....YY..........YY....
...YYYY........YYYY...
..YYYYYY......YYYYYY..
..YYYYYY......YYYYYY..
.YYYYYYYY....YYYYYYYY.
.YYYYYYYY....YYYYYYYY.
YYYYYYYYYY..YYYYYYYYYY
yyyyyyyyyy..yyyyyyyyyy
...yy..W........W.yy..`,
    ],
  },
  {
    id: "star", label: "Star", movement: "zoom in", fps: 4,
    words: ["star", "stars", "starlight", "shine", "shining", "shines", "bright", "twinkle", "twinkling", "east", "wise"],
    frames: [
`.........Y.........
.........Y.........
........YYY........
........YYY........
.......YYYYY.......
YYYYYYYYYYYYYYYYYYY
..YYYYYYYWYYYYYYY..
....YYYYWWWYYYY....
......YYYWYYY......
.....YYYYYYYYY.....
....YYYYY.YYYYY....
...YYYY.....YYYY...
..YYY.........YYY..
.YY.............YY.`,
`W........Y........W
.........Y.........
........YYY........
........YYY........
.......YYYYY.......
YYYYYYYYYYYYYYYYYYY
..YYYYYYYWYYYYYYY..
....YYYYWWWYYYY....
......YYYWYYY......
.....YYYYYYYYY.....
....YYYYY.YYYYY....
...YYYY.....YYYY...
..YYY.........YYY..
.YY.............YYW`,
    ],
  },
  {
    id: "snowflake", label: "Snowflake", movement: "none", fps: 3,
    words: ["snow", "snowflake", "snowflakes", "snowing", "flurries", "flakes", "frost", "frosty", "winter", "icy", "cold", "white"],
    colours: { X: "#c0e8ff" },
    frames: [
`.......X.......
....X..X..X....
.....X.X.X.....
..X...XXX...X..
...X..XWX..X...
....XXXWXXX....
.XXXXXWWWXXXXX.
....XXXWXXX....
...X..XWX..X...
..X...XXX...X..
.....X.X.X.....
....X..X..X....
.......X.......`,
`...X.......X...
....X..L..X....
.....X.L.X.....
..L...XXX...L..
...L..XWX..L...
....XXXWXXX....
.LLXXXWWWXXXLL.
....XXXWXXX....
...L..XWX..L...
..L...XXX...L..
.....X.L.X.....
....X..L..X....
...X.......X...`,
    ],
  },
  {
    id: "tree", label: "Christmas tree", movement: "zoom in", fps: 3,
    words: ["tree", "trees", "pine", "fir", "evergreen", "tannenbaum", "branches"],
    frames: [
`........Y........
.......YYY.......
........G........
.......GGG.......
......GRGGG......
.....GGGGGBG.....
......GGGGG......
.....GGYGGGG.....
....GGGGGRGGG....
...GBGGGGGGGGG...
.....GGGGGGG.....
....GGGRGGGYGG...
...GGGGGGGGGGGG..
..GGYGGGGBGGGGRG.
.GGGGGGGGGGGGGGGG
.......bbb.......
.......bbb.......`,
`........W........
.......YYY.......
........G........
.......GGG.......
......GGGYG......
.....GRGGGGG.....
......GGGGG......
.....GGGGBGG.....
....GYGGGGGGG....
...GGGGGRGGGYG...
.....GGGGGGG.....
....GBGGGGGRGG...
...GGGGYGGGGGGG..
..GGGGGGGGRGGGBG.
.GGRGGGGGGGGGGGGG
.......bbb.......
.......bbb.......`,
    ],
  },
  {
    id: "gift", label: "Present", movement: "bounce", fps: 3,
    words: ["gift", "gifts", "present", "presents", "toy", "toys", "wrapped", "giving"],
    frames: [
`.................
.................
.................
.....YY...YY.....
......YY.YY......
.......YYY.......
.UUUUUUUYUUUUUUU.
.UUUUUUUYUUUUUUU.
..UUUUUUYUUUUUU..
..UUUUUUYUUUUUU..
..UUUUUUYUUUUUU..
..YYYYYYYYYYYYY..
..UUUUUUYUUUUUU..
..UUUUUUYUUUUUU..
..UUUUUUYUUUUUU..`,
`.....YY...YY.....
......YY.YY......
.......YYY.......
.UUUUUUUYUUUUUUU.
.UUUUUUUYUUUUUUU.
...W....W....W...
..W...W...W...W..
.................
..UUUUUUYUUUUUU..
..UUUUUUYUUUUUU..
..UUUUUUYUUUUUU..
..YYYYYYYYYYYYY..
..UUUUUUYUUUUUU..
..UUUUUUYUUUUUU..
..UUUUUUYUUUUUU..`,
    ],
  },
  {
    id: "candle", label: "Candle", movement: "none", fps: 6,
    words: ["candle", "candles", "candlelight", "flame", "glow", "glowing", "fire", "fireside"],
    frames: [
`.....Y.....
....YYY....
....YOY....
...YYOYY...
....YYY....
.....k.....
...WWWWW...
...WWWWW...
...WRWWW...
...WRWWW...
...WWWWW...
...WWWWW...
.GGGGGGGGG.
..GGGGGGG..`,
`......Y....
....YYY....
...YYOY....
...YOOYY...
....YYY....
.....k.....
...WWWWW...
...WWWWW...
...WRWWW...
...WRWWW...
...WWWWW...
...WWWWW...
.GGGGGGGGG.
..GGGGGGG..`,
`....Y......
....YYY....
....YOYY...
...YYOOY...
....YYY....
.....k.....
...WWWWW...
...WWWWW...
...WRWWW...
...WRWWW...
...WWWWW...
...WWWWW...
.GGGGGGGGG.
..GGGGGGG..`,
    ],
  },
  {
    id: "heart", label: "Heart", movement: "none", fps: 4,
    words: ["love", "loved", "loving", "heart", "hearts", "darling", "sweetheart", "kiss"],
    frames: [
`...RRR...RRR...
..RRRRR.RRRRR..
.RRWRRRRRRRRRR.
.RWRRRRRRRRRRR.
.RRRRRRRRRRRRR.
..RRRRRRRRRRR..
...RRRRRRRRR...
....RRRRRRR....
.....RRRRR.....
......RRR......
.......R.......`,
`...............
...RR.....RR...
..RRRR...RRRR..
..RWRRRRRRRRR..
..RRRRRRRRRRR..
...RRRRRRRRR...
....RRRRRRR....
.....RRRRR.....
......RRR......
.......R.......
...............`,
    ],
  },
  {
    id: "house", label: "House", movement: "none", fps: 3,
    words: ["home", "house", "chimney", "fireplace", "hearth", "town"],
    frames: [
`................K...
...............K....
................K...
...........W...rr...
..........WWW..rr...
.........WWWWW.rr...
........WWWWWWWWr...
.......WWWWWWWWWWW..
......WWWWWWWWWWWWW.
.......RRRRRRRRRRR..
.......RYYRRRRRYYR..
.......RYYRRbbRYYR..
.......RRRRRbbRRRR..
.......RRRRRbbRRRR..`,
`...............K....
................K...
...............K....
...........W...rr...
..........WWW..rr...
.........WWWWW.rr...
........WWWWWWWWr...
.......WWWWWWWWWWW..
......WWWWWWWWWWWWW.
.......RRRRRRRRRRR..
.......ROORRRRROOR..
.......ROORRbbROOR..
.......RRRRRbbRRRR..
.......RRRRRbbRRRR..`,
    ],
  },
  {
    id: "angel", label: "Angel", movement: "bounce", fps: 3,
    words: ["angel", "angels", "heaven", "heavenly", "herald", "hark", "glory", "gloria", "halo"],
    frames: [
`......YYYY.......
.....Y....Y......
......SSSS.......
.....SkSSkS......
WW...SSSSSS...WW.
WWW...SSSS...WWW.
.WWW.WWWWWW.WWW..
..WWWWWWWWWWWW...
...WWWWWWWWWW....
.....WWWWWW......
....WWWWWWWW.....
....WWWWWWWW.....
...WWWWWWWWWW....
...WWWWWWWWWW....`,
`......YYYY.......
.....Y....Y......
......SSSS.......
.....SkSSkS......
.....SSSSSS......
WWWW..SSSS..WWWW.
.WWWWWWWWWWWWWW..
...WWWWWWWWWW....
...WWWWWWWWWW....
.....WWWWWW......
....WWWWWWWW.....
....WWWWWWWW.....
...WWWWWWWWWW....
...WWWWWWWWWW....`,
    ],
  },
  {
    id: "moon", label: "Moon and stars", movement: "none", fps: 2,
    words: ["moon", "moonlight", "night", "nights", "midnight", "sky", "skies", "evening"],
    frames: [
`.....YYYY.......W...
...YYYY.............
..YYYY..........Y...
.YYYY...............
.YYY........W.......
YYYY................
YYYY................
YYYY.............W..
.YYY................
.YYYY.......Y.......
..YYYYY.............
...YYYYYY..W........
.....YYYYYY.........`,
`.....YYYY...........
...YYYY.........W...
..YYYY..............
.YYYY.......Y.......
.YYY................
YYYY.............W..
YYYY................
YYYY................
.YYY........W.......
.YYYY...............
..YYYYY..........Y..
...YYYYYY...........
.....YYYYYY.........`,
    ],
  },
  {
    id: "train", label: "Toy train", movement: "left", fps: 6,
    words: ["train", "trains", "choo", "railroad", "engine", "track", "tracks"],
    frames: [
`.....KK..................
....K..K.................
.....KK..................
..kk.............RRRRR...
..kk.............R.L.R...
..kk.............R...R...
.UUUUUUUUUUUUUUUURRRRR...
.UUUUUUUUUUUUUUUURRRRRR..
.UUYYYYYYYYYYYYYUURRRRR..
YUUUUUUUUUUUUUUUURRRRRR..
.UUUUUUUUUUUUUUUURRRRRR..
..kKk..kKk..kKk...kKkk...
..kkk..kkk..kkk...kkkk...
KKKKKKKKKKKKKKKKKKKKKKKKK`,
`...KK....................
..K..K...................
...KK.......K............
..kk.............RRRRR...
..kk.............R.L.R...
..kk.............R...R...
.UUUUUUUUUUUUUUUURRRRR...
.UUUUUUUUUUUUUUUURRRRRR..
.UUYYYYYYYYYYYYYUURRRRR..
YUUUUUUUUUUUUUUUURRRRRR..
.UUUUUUUUUUUUUUUURRRRRR..
..kkK..kkK..kkK...kkKk...
..Kkk..Kkk..Kkk...Kkkk...
KKKKKKKKKKKKKKKKKKKKKKKKK`,
    ],
  },
  {
    id: "drum", label: "Drum", movement: "none", fps: 4,
    words: ["drum", "drums", "drummer", "drumming", "beat", "march", "marching"],
    frames: [
`.T...........T...
..T.........T....
...T.......T.....
....T.....T......
..WWWWWWWWWWWWW..
.WWWWWWWWWWWWWWW.
.RRYRRRYRRRYRRRR.
.RRRYRYRRRYRYRRR.
.RRRRYRRRRRYRRRR.
.RRRYRYRRRYRYRRR.
.RRYRRRYRRRYRRRR.
.YYYYYYYYYYYYYYY.`,
`.................
.................
.......Y...Y.....
..TTTTTW...WTTTTT
..WWWWWWWWWWWWW..
.WWWWWWWWWWWWWWW.
.RRYRRRYRRRYRRRR.
.RRRYRYRRRYRYRRR.
.RRRRYRRRRRYRRRR.
.RRRYRYRRRYRYRRR.
.RRYRRRYRRRYRRRR.
.YYYYYYYYYYYYYYY.`,
    ],
  },
  {
    id: "gingerbread", label: "Gingerbread figure", movement: "bounce", fps: 3,
    words: ["gingerbread", "cookie", "cookies", "baking", "bake", "baked"],
    frames: [
`.....BBBBB.....
....BBBBBBB....
....BWBBBWB....
....BBBBBBB....
....BWWWWWB....
.....BBBBB.....
.W.BBBBBBBBB.W.
.BBBBBRBRBBBBB.
.....BBBBB.....
.....BBGBB.....
.....BBBBB.....
.....BBGBB.....
....BBB.BBB....
...BBB...BBB...
...WBB...BBW...`,
`.....BBBBB..W..
....BBBBBBB.B..
....BWBBBWB.B..
....BBBBBBB.B..
....BWWWWWB.B..
.....BBBBB..B..
.W.BBBBBBBBBB..
.BBBBBRBRBBBB..
.....BBBBB.....
.....BBGBB.....
.....BBBBB.....
.....BBGBB.....
....BBB.BBB....
...BBB...BBB...
...WBB...BBW...`,
    ],
  },
  {
    id: "ornament", label: "Ornament", movement: "wiggle", fps: 3,
    words: ["ornament", "ornaments", "bauble", "baubles", "decorate", "decorations", "deck", "trim", "tinsel"],
    frames: [
`......YY.......
.....Y..Y......
......KK.......
.....KKKK......
...VVVVVVVV....
..VVWVVVVVVV...
.VVWVVVVVVVVV..
.VVVVVVVVVVVV..
.YYYYYYYYYYYY..
.VVVVVVVVVVVV..
.VVVVVVVVVVVV..
..VVVVVVVVVV...
...VVVVVVVV....
.....VVVV......`,
`......YY.......
.....Y..Y......
......KK.......
.....KKKK......
...VVVVVVVV....
..VVVVVVVVVV...
.VVVVVVVVVWVV..
.VVVVVVVVWVVV..
.YYYYYYYYYYYY..
.VVVVVVVVVVVV..
.VVVVVVVVVVVV..
..VVVVVVVVVV...
...VVVVVVVV....
.....VVVV......`,
    ],
  },
  {
    id: "wreath", label: "Wreath", movement: "none", fps: 3,
    words: ["wreath", "wreaths", "holly", "ivy", "mistletoe", "bough", "boughs", "garland"],
    frames: [
`.....GGGGGG.....
...GGgGGGGgGG...
..GgGRGGGGGRgG..
.GGGG......GGGG.
.GgG........GgG.
GGRG........GRGG
GGG..........GGG
GGG..........GGG
GGRG........GRGG
.GgG........GgG.
.GGGG......GGGG.
..GgGGGRRGGGgG..
...GGgRRRRgGG...
.....RR..RR.....
....RR....RR....`,
`.....GGGGGG.....
...GGgGGGGgGG...
..GgGWGGGGGRgG..
.GGGG......GGGG.
.GgG........GgG.
GGRG........GWGG
GGG..........GGG
GGG..........GGG
GGWG........GRGG
.GgG........GgG.
.GGGG......GGGG.
..GgGGGRRGGGgG..
...GGgRRRRgGG...
.....RR..RR.....
....RR....RR....`,
    ],
  },
  {
    id: "manger", label: "Manger under a star", movement: "zoom in", fps: 2,
    words: ["manger", "infant", "baby", "born", "bethlehem", "stable", "nativity", "shepherds", "holy"],
    frames: [
`.........Y.........
........YYY........
.....YYYYWYYYY.....
........YYY........
.........Y.........
.........Y.........
...................
.......SSSS........
.....WWWSSWWW......
....YyYWWWWWWYyY...
...YyYyYyYyYyYyY...
....BBBBBBBBBBB....
.....B.......B.....
....B.........B....`,
`.........W.........
.........Y.........
....YYYYYWYYYYY....
.........Y.........
.........Y.........
.........Y.........
.........Y.........
.......SSSS........
.....WWWSSWWW......
....YyYWWWWWWYyY...
...YyYyYyYyYyYyY...
....BBBBBBBBBBB....
.....B.......B.....
....B.........B....`,
    ],
  },
  {
    id: "stocking", label: "Stocking", movement: "wiggle", fps: 2,
    words: ["stocking", "stockings", "hung", "hang"],
    frames: [
`..WWWWWWW.......
..WWWWWWW.......
...RRRRR........
...RRRRR........
...RRGRR........
...RRRRR........
...RRRRR........
...RRRRRR.......
...RRRRRRRRR....
..RRRRRRRRRRR...
..RRRRRRRRRRR...
...RRRRRRRRR....`,
`..WWWWWWW.......
..WWWWWWW.......
...RRRRR........
...RRRRR........
...RRRRR........
...RRGRR........
...RRRRR........
...RRRRRR.......
...RRRRRRRRR....
..RRRRRRRRRRR...
..RRRRRRRRRRR...
...RRRRRRRRR....`,
    ],
  },
  {
    id: "candy-cane", label: "Candy cane", movement: "none", fps: 4,
    words: ["candy", "cane", "canes", "peppermint", "sweets", "sugar", "sugarplum", "sugarplums"],
    frames: [
`....RRWW....
..WWRRWWRR..
.RR......WW.
.WW......RR.
.RR......WW.
.WW.........
.RR.........
.WW.........
.RR.........
.WW.........
.RR.........
.WW.........
.RR.........
.WW.........`,
`....WWRR....
..RRWWRRWW..
.WW......RR.
.RR......WW.
.WW......RR.
.RR.........
.WW.........
.RR.........
.WW.........
.RR.........
.WW.........
.RR.........
.WW.........
.RR.........`,
    ],
  },
];

const byId = new Map(SPRITES.map((s) => [s.id, s]));
const decoded = new Map<string, PictureImage[]>();

function hexRgb(hex: string): [number, number, number] {
  return [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16)) as [number, number, number];
}

/** A sprite's frames as images the Pictures effect draws, decoded once. */
export function spriteFrames(id: string): PictureImage[] | undefined {
  const cached = decoded.get(id);
  if (cached) return cached;
  const sprite = byId.get(id);
  if (!sprite) return undefined;
  const colours = { ...SHARED, ...sprite.colours };
  const frames = sprite.frames.map((frame) => {
    const rows = frame.split("\n");
    const width = Math.max(...rows.map((r) => r.length)), height = rows.length;
    const data: number[] = [];
    for (const row of rows) {
      for (let x = 0; x < width; x++) {
        const c = colours[row[x] ?? "."];
        data.push(...(c ? [...hexRgb(c), 255] : [0, 0, 0, 0]));
      }
    }
    return { width, height, data };
  });
  decoded.set(id, frames);
  return frames;
}

export function spriteById(id: string): Sprite | undefined {
  return byId.get(id);
}

const byWord = new Map(SPRITES.flatMap((s) => s.words.map((w) => [w, s] as const)));

/**
 * The sprite a sung line calls up: its first word the library knows ("boots", "sleigh"), read
 * plainly and without a plural or possessive "s" ("reindeers", "Santa's").
 */
export function spriteFor(line: string): Sprite | undefined {
  for (const raw of line.toLowerCase().split(/[^a-z']+/)) {
    const word = raw.replace(/'s$|'$/, "");
    const sprite = byWord.get(word) ?? (word.endsWith("s") ? byWord.get(word.slice(0, -1)) : undefined);
    if (sprite) return sprite;
  }
  return undefined;
}
